version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped	
    environment:
      MONGO_INITDB_ROOT_USERNAME: hondanho
      MONGO_INITDB_ROOT_PASSWORD: hondanho

  mongo-express:
    image: mongo-express
    restart: unless-stopped	
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: hondanho
      ME_CONFIG_MONGODB_ADMINPASSWORD: hondanho
      ME_CONFIG_MONGODB_URL: mongodb://hondanho:hondanho@mongo:27017/